### ISSUE TITLE
cytominer-database should publish wheels

### ISSUE THREAD

**Issue by mcquin** [0x00B1/persistence#54]
Although deployment to PyPI is enabled in Travis, it doesn't appear to be the case that the package wheels are being published. I believe this is the cause:

```
on:
   tags: true
   distributions: "sdist bdist_wheel"
   repo: cytomining/cytominer-database
```

The `distributions` section should not be contained within `on`:

```
 distributions: "sdist bdist_wheel"
 on:
   tags: true
   repo: cytomining/cytominer-database
```
